# Generated by Django 2.0.2 on 2019-11-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Ammonites',
        ),
    ]
