# Generated by Django 2.0.2 on 2019-11-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191103_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ammonites',
            new_name='Products',
        ),
    ]
